name: Update readme with Wakatime stats

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_COMMIT: "False"
          SHOW_DAYS_OF_WEEK: "False"
